# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_multiplechoisequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question')),
            ],
            bases=('courses.question',),
        ),
        migrations.RenameModel(
            old_name='MultipleChoiseQuestion',
            new_name='MultipleChoiceQuestion',
        ),
    ]
